---
title: "Kelp vs Urchins"
author: Nick Toimieri
date: sys.date()
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: true
    fig_caption: true
fontsize: 11pt

---

```{r SETUP, include=FALSE}
# A bunch of initial set up junk

rm(list = ls())

##### knitr stuff and libraries ####
source("R-functions-ocnms.r")

# Paths for files
setwd('..')
HomeFile = getwd()
# HomeFile = "C:/Users/nick.tolimieri/Documents/GitHub/OCNMS/"

Fig_Loc = paste0(HomeFile,"/Plots/")
Data_Loc = paste0(HomeFile,"/Data/")
Results_Loc = paste0(HomeFile,"/Results/")
Other_Files = paste0(HomeFile,"/Other Files/")

# tools in use 
library(knitr)
# library(tidyr)
# library(dplyr)
library(tidyverse)
library(stringr)
library(tinytex) # for pdfs
library(RColorBrewer)
# display.brewer.all(colorblindFriendly = TRUE)
library(readxl)

# stats packages etc
library(vegan)
library(BiodiversityR)
# library(pracma)
# library(factoextra)

# install.packages("remotes")
# for Bray curtis with no spp in common.
# remotes::install_github("phytomosaic/ecole")
library(ecole)

# options
knitr::opts_chunk$set(
  fig.path = Fig_Loc,
  cache.path = 'cache/graphics-', 
  echo=FALSE,
  error=FALSE,
  include = TRUE,
  dev='png',
  dpi=300,
  warning=FALSE,
  #out.width = '100%',
  fig.align='center'
  
  )

# just to keep track of when I ran things.

Last_Run0 = Sys.time()
Last_Run = str_replace(Last_Run0, ":", ".")
Last_Run = str_replace(Last_Run, ":", ".")
capture.output(Last_Run, file = 'Last_Run.txt') # over-writes previous file

par(ps=10, cex=1)

# load some external functions
# source("R-functions-ocnms.r")

```

# Triggers and settings

```{r Triggers-and-Settings}

# bring in settings from previous univariate figure or set
# maintain consistency between files

settings = readRDS(paste0(Data_Loc,'settings.rds') )

min.vis = as.numeric(settings['min.vis'])
years = as.numeric(unlist(settings['years']))
site.col = data.frame(settings['site.col'])
colnames(site.col) = c('site','col')
sites = site.col$site
year.pch = data.frame(settings['year.pch'])
colnames(year.pch) = c('year','pch','col')

# Set common stuff for ordinations here ####
# Options are: NA, "sqrt", "4th-root","log"
# for 'log' the transform is actually log(x+1), need the log+1 because of zeros.

kelp.transform = 'log'
fish.transform = 'log'
invert.transform = 'log'
nperm  = 999

# Some csv files for naming later

fish_codes = data.frame(read.csv( paste0(Data_Loc,"spp_codes_fish.csv") ))
swath_codes = data.frame(read.csv( paste0(Data_Loc,"spp_codes_swath.csv") ))
kelp_codes = data.frame(read.csv( paste0(Data_Loc,"spp_codes_kelp.csv") ))

```

# Import Data

```{r import-kelp-urchins}

df_transect1 = readRDS(paste0(Data_Loc,'Data_Inverts_Kelp_transect_wide.rds')) %>% 
              filter(site %in% sites) 
              
df_transect2 = df_transect1[,c('site','year','transect','area','zone', 
                             'NERLUE','MACPYR', 'PTECAL',
                             'purple urchin','red urchin','green urchin')]

df_transect =  df_transect2 %>%
                  pivot_longer(NERLUE:PTECAL , names_to = 'kelp_spp', values_to = 'kelp_density') %>%
                    mutate(kelp_spp = factor(kelp_spp, levels=c('MACPYR','NERLUE','PTECAL'))) %>%
                  pivot_longer('purple urchin':'green urchin' , 
                               names_to = 'urchin_spp', values_to = 'urchin_density') %>%
                    mutate(urchin_spp = factor(urchin_spp, 
                                               levels=c('purple urchin','red urchin','green urchin'))) 





```

# BY SPECIES

## Transect level

```{r kelp-vs-urchins-transet}
library(cowplot)
library(viridis)


pl <- df_transect %>%
     filter(zone == 5) %>%
  ggplot(aes(urchin_density,kelp_density,col=site))+
  # geom_point(size=2.5, pch=kelp_urchins_long$yr)+
  geom_point(size=1)+
  theme_minimal()+
  # scale_color_manual(values=color5 , pch=kelp_urchins_long$yr)+
  scale_color_manual(values=site.col$col )+
  facet_grid(urchin_spp ~ kelp_spp)+
  theme_bw()+
  theme( legend.title = element_blank(),
         legend.text = element_text(size = 7),
         legend.key.size =  unit(0.25,"point"),
         legend.background = element_blank(),
         axis.text = element_text( size = 8 ),
         axis.text.x = element_text( size = 8 ),
         strip.background = element_blank(),
         strip.text = element_text(size = 8),
         strip.placement = "inside",
         panel.grid  = element_blank(),
         panel.spacing = unit(0.5, "lines"),
         )+
  labs(x="Urchin Density",y=("Log (Kelp Density+1)"),col="Site")
pl



```
## Site level 

```{r kelp-urchins-site}



kelp_site   <- df_transect %>% group_by(year, site, zone, kelp_spp) %>% 
               summarise(kelp_mean = mean(kelp_density) ) 
                # rename(mean = kelp_mean) %>%
                # rename(spp = kelp_spp)
                # 
urchin_site <- df_transect %>% group_by(year, site, zone,  urchin_spp) %>% 
               summarise(urchin_mean = mean(urchin_density) ) 
                # rename(mean = urchin_mean) %>%
                # rename(spp = urchin_spp)



df_site <- kelp_site %>% left_join(., urchin_site, by=c('year'='year', 'site'='site','zone'='zone'))
dim(df_site)


pl <- df_site %>%
     filter(zone == 5) %>%
  ggplot(aes(urchin_density,kelp_density,col=site))+
  # geom_point(size=2.5, pch=kelp_urchins_long$yr)+
  geom_point(size=1)+
  theme_minimal()+
  # scale_color_manual(values=color5 , pch=kelp_urchins_long$yr)+
  scale_color_manual(values=site.col$col )+
  facet_grid(urchin_spp ~ kelp_spp)+
  theme_bw()+
  theme( legend.title = element_blank(),
         legend.text = element_text(size = 7),
         legend.key.size =  unit(0.25,"point"),
         legend.background = element_blank(),
         axis.text = element_text( size = 8 ),
         axis.text.x = element_text( size = 8 ),
         strip.background = element_blank(),
         strip.text = element_text(size = 8),
         strip.placement = "inside",
         panel.grid  = element_blank(),
         panel.spacing = unit(0.5, "lines"),
         )+
  labs(x="Urchin Density",y=("Log (Kelp Density+1)"),col="Site")
pl




```