---
title: "Relief_GS"
output: html_document
---


```{r setup,message=FALSE, warning=FALSE}
#to load data make sure directory is set to knit from project directory
knitr::opts_chunk$set(message=FALSE, warning=FALSE)
 
library(here)
library(tidyverse)
library(knitr)
library(viridis)
 
substrate_codes <- read_csv(here("Data","CSV_2015_on","substrate_codes.csv"))
 
#2016 --> 2019
dat.relief <- read_csv(here("Data","CSV_2015_on","NWFSC_UPC_ALLYEARS_data_2019.csv"), col_types = cols(SIDE = col_character())) %>% 
              filter(CATEGORY == "RELIEF") %>%
              select(1:20) %>%
              rename(DEPTH.FT= "DEPTH (FT)")  %>%
              #mutate(QUADRAT = NA, PERCENT.COVER = NA) %>% #will circle back tothis and get % cover for 2016 to 2019 data 
              group_by(SITE, YEAR,SIDE,ZONE,TRANSECT, CLASSCODE) %>% #combine across segments 
              summarise(COUNT = sum(COUNT)) %>%
              spread(CLASSCODE, COUNT) %>%
              ungroup() %>%
              replace(is.na(.), 0) %>%
              dplyr::mutate(Sum = rowSums(.[,6:9])) %>%
              tidyr::gather(6:9, key = "CLASSCODE", value = "COUNT") %>%
              mutate(percent_cover = COUNT/Sum, CLASSCODE = factor(CLASSCODE, levels=c("0-10cm","10cm-1m","1m-2m",">2m")))


```

- dat_relief is summarized by percent relief/transect
```{r}
dat.zone.summary <- dat.relief %>%
  group_by(YEAR,SITE,ZONE,CLASSCODE) %>% 
  summarise(mean_percent_cover = mean(percent_cover), variance = var(percent_cover)) %>% 
  ungroup() %>%
  mutate(SITE = factor(SITE, levels = c("Destruction Island","Cape Johnson", "Cape Alava","Tatoosh Island","Neah Bay")))
```

```{r}
ggplot(dat.zone.summary,aes(x=YEAR)) +
  geom_bar(aes(y=mean_percent_cover, fill= CLASSCODE), position="fill", stat="identity",width = 0.95
           )+
  scale_fill_viridis(discrete = T) + #,  guide = guide_legend(reverse = TRUE), name = "Stock") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "left",aspect.ratio = 3/1)  +
  theme_classic()+
  ylab("Mean Percent Cover") +
  xlab("Year") +
  facet_grid(ZONE~SITE) +
 # coord_flip() +
  scale_x_continuous(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0)) +
  theme(legend.position="left") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), strip.text.x = element_text(size = 7))

```



```{r}
dat.site.summary <- dat.relief %>%
  group_by(SITE,CLASSCODE) %>% 
  summarise(mean_percent_cover = mean(percent_cover), variance = var(percent_cover)) %>% 
  ungroup() %>%
  mutate(SITE = factor(SITE, levels = c("Destruction Island","Cape Johnson", "Cape Alava","Tatoosh Island","Neah Bay")))
```

```{r}
ggplot(dat.site.summary,aes(x=SITE)) +
  geom_bar(aes(y=mean_percent_cover, fill= CLASSCODE), position="fill", stat="identity",width = 0.95
           )+
  scale_fill_viridis(discrete = T) + #,  guide = guide_legend(reverse = TRUE), name = "Stock") +
  theme(axis.text.x = element_text(angle = 90, hjust = 1), legend.position = "left",aspect.ratio = 3/1)  +
  theme_classic()+
  ylab("Mean Percent Cover") +
  xlab("Year") +
  #facet_wrap(~ZONE, nrow =1) +
  scale_x_discrete(expand = c(0,0))+
  scale_y_continuous(expand = c(0,0)) +
  theme(legend.position="left") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), strip.text.x = element_text(size = 7))

```













 