---
title: "Annual update - UPC"
author: Nick Toimieri
date: sys.date()
output: 
  html_document:
    toc: true
    toc_float: true
    toc_depth: 5
    number_sections: true
    fig_caption: true
fontsize: 11pt
---
# NOTES

Annual replotting of UPC data

# DATA YEAR 

Set the data_year year

```{r SETUP, include=FALSE}
rm(list = ls())
library(here)
library(flextable)
library(tidyverse)
repo_dir = "~/GitHub/OCNMS"
# repo_dir = here::here() # for MAC users
home_dir = paste0(repo_dir,"/_00_Annual-Update/")
# setwd(home_dir) # set home dir to annual update folder
data_year = 2025
source("settings.r")
source("R-functions-ocnms.r")

################################################################################

knitr::opts_chunk$set(
  root.dir = home_dir,
  fig.path = fig_dir,
  cache.path = 'cache/graphics-', 
  echo=FALSE,
  error=FALSE,
  include = TRUE,
  dev='png',
  dpi=300,
  warning=FALSE,
  #out.width = '100%',
  fig.align='center'
)

```

# Bring in data

```{r load-data}

upc = data.frame(read.csv( paste0(data_dir,'NWFSC_UPC_ALLYEARS_data_2025.csv'), header=T))

upc = upc %>% 
  mutate(depth_m = `DEPTH..FT.` / 3.281) %>%
  dplyr::select(-c(entry.order, Cntrl.a, notes, problems, `DEPTH..FT.`, `DEPTH..M.`) )

upc$CLASSCODE[upc$CLASSCODE=="sand"] <- "SAND"
upc$CLASSCODE[upc$CLASSCODE=="cob"] <- "COB"
upc$CLASSCODE[upc$CLASSCODE=="ptero"] <- "PTERO"
upc$CLASSCODE[upc$CLASSCODE=="shell"] <- "SHELL"

upc$CLASSCODE[upc$CLASSCODE==">2M"] = ">2m"
upc$CLASSCODE[upc$CLASSCODE=="<2M"] = "1m-2m"
upc$CLASSCODE[upc$CLASSCODE=="<2m"] = "1m-2m"
upc$CLASSCODE[upc$CLASSCODE=="0-10m"] = "0-10cm"

upc_transect = upc %>% group_by(YEAR, SITE, SIDE, ZONE, TRANSECT, CATEGORY, CLASSCODE) %>%
  summarize(count = sum(COUNT)) %>%
  mutate(transect_id = paste(YEAR,SITE,SIDE,ZONE,TRANSECT,sep="_"))

upc_relief = upc_transect %>% filter(CATEGORY == 'RELIEF')
upc_subs = upc_transect %>% filter(CATEGORY == 'SUBSTRATE')
upc_cover = upc_transect %>% filter(CATEGORY == 'COVER')

# error check
unique(upc_subs$CLASSCODE)
unique(upc_relief$CLASSCODE)
unique(upc_cover$CLASSCODE)

write.csv(upc_transect, paste0(data_dir,"Summarized_Data_UPC_by_Transect.csv"), row.names = F)


```

## Relief bar chart
 
```{r relief-prep}
# total points by transect to convert to proportions
x_relief = upc_relief %>%
 group_by(YEAR, SITE, ZONE, transect_id) %>% 
  summarize(SUM = sum(count)) 
x_relief

# fix some class codes
# order them for plotting
upc_relief$CLASSCODE = factor(upc_relief$CLASSCODE, 
                                 levels = c("0-10cm", "10cm-1m","1m-2m", ">2m"))
unique(upc_relief$CLASSCODE)

# combine files and calculate mean proportion for each classcode/row
upc_relief$total = x_relief$SUM[ match(upc_relief$transect_id,x_relief$transect_id )]
upc_relief$prop = upc_relief$count/upc_relief$total

# convert to year by site means

relief_year_site = upc_relief %>%
  group_by(YEAR, SITE, CLASSCODE) %>%
  summarize(mean_prop = mean(prop))

```

```{r plot-relief, fig.width=3.5,fig.height=5}

relief_year_site$year = as.factor(relief_year_site$YEAR)
relief_year_site$site = factor(relief_year_site$SITE,
                               levels =c("Tatoosh Island","Neah Bay",
                                          "Cape Alava", "Cape Johnson",
                                          "Destruction Island"))

relief.plot <- ggplot(relief_year_site,aes(x=year)) +
        geom_bar(aes(y=mean_prop, fill= CLASSCODE), 
                 position="fill", stat="identity",width = 0.75, colour="black")+
        # scale_fill_manual(values = site.col$col,
        #                   labels = c('0-0.1 m','0.1-1 m', '1-2 m', '> 2 m')) +  
        theme(legend.position = "left", aspect.ratio = 3/1)  +
        theme_bw()+
        ylab("Proportion") +
        xlab("") +
        # scale_x_discrete(expand = c(0,0), labels=c("DI","CJ","CA","TI","NB"))+
        # scale_y_continuous(expand = c(0,0)) +
        facet_wrap(facets = 'site', ncol=2) +
        theme(legend.title = element_blank(),
              legend.key.size = unit(0.3, "cm"),
              legend.text = element_text(size=8 ),
              axis.text.x = element_text(size=8, angle=90, vjust=0.4), 
              strip.text.x = element_text(size = 8),
              legend.position = 'inside',
              legend.position.inside = c(0.7,0.1))

relief.plot

```

## Substratum bar chart

```{r substratum-prep}
# check counts by transect

x_subs = upc_subs %>%
 group_by(YEAR, SITE, ZONE, transect_id) %>% 
  summarize(SUM = sum(count)) 
# x_subs
# quick plot

# combine files and calculate mean proportion for each classcode/row
upc_subs$total = x_subs$SUM[ match(upc_subs$transect_id, x_subs$transect_id )]
upc_subs$prop = upc_subs$count/upc_subs$total

subs_year_site = upc_subs %>%
  group_by(YEAR, SITE, CLASSCODE) %>%
  summarize(percent = mean(prop)*100) 
```

```{r plot-substrate, fig.width=3.5,fig.height=5}
subs_year_site$year = as.factor(subs_year_site$YEAR)
subs_year_site$site = factor(subs_year_site$SITE,
                               levels =c("Tatoosh Island","Neah Bay",
                                          "Cape Alava", "Cape Johnson",
                                          "Destruction Island"))

subs_col = RColorBrewer::brewer.pal(12,'Paired')[c(2,4,6,8,10)]
subs_year_site$CLASSCODE = factor(subs_year_site$CLASSCODE,
                                  levels=rev(c("NOT_DONE","SAND","BEDRK", "COB", 'BOULD' )))

  
subs.plot <- ggplot(subs_year_site,aes(x=year)) +
        geom_bar(aes(y=percent, fill= CLASSCODE), 
                 position="fill", stat="identity",width = 0.75, colour="black")+
        # scale_fill_manual(values = subs_col,
        #                   labels = c('0-0.1 m','0.1-1 m', '1-2 m', '> 2 m')) +  
        theme(legend.position = "left", aspect.ratio = 3/1)  +
        theme_bw()+
        ylab("Proportion") +
        xlab("") +
        # scale_x_discrete(expand = c(0,0), labels=c("DI","CJ","CA","TI","NB"))+
        # scale_y_continuous(expand = c(0,0)) +
        facet_wrap(facets = 'site', ncol=2) +
        theme(legend.title = element_blank(),
              legend.key.size = unit(0.3, "cm"),
              legend.text = element_text(size=8 ),
              axis.text.x = element_text(size=8, angle=90, vjust=0.4), 
              strip.text.x = element_text(size = 8),
              legend.position = 'inside',
              legend.position.inside = c(0.7,0.1))

subs.plot

```


## Cover Bar chart

```{r cover-prep}

x_cover = upc_cover %>%
 group_by(YEAR, SITE, ZONE, transect_id) %>% 
  summarize(SUM = sum(count)) 

# quick plot

upc_cover$total = x_cover$SUM[ match(upc_cover$transect_id, x_cover$transect_id )]
upc_cover$percent = upc_cover$count/upc_cover$total*100

cover_year_site = upc_cover %>%
  group_by(YEAR, SITE, CLASSCODE) %>%
  summarize(percent = mean(percent)) 

```
### All cover types.  Not filtered. Just to see.

```{r plot-cover}

cover_year_site$year = as.factor(cover_year_site$YEAR)
cover_year_site$site = factor(cover_year_site$SITE,
                               levels =c("Tatoosh Island","Neah Bay",
                                          "Cape Alava", "Cape Johnson",
                                          "Destruction Island"))

subs_col = RColorBrewer::brewer.pal(12,'Paired')[c(2,4,6,8,10)]
  
subs.plot <- ggplot(cover_year_site,aes(x=year)) +
        geom_bar(aes(y=percent, fill= CLASSCODE), 
                 position="fill", stat="identity",width = 0.75, colour="black")+
        #
        theme(legend.position = "left", aspect.ratio = 3/1)  +
        theme_bw()+
        ylab("Proportion") +
        xlab("") +
        # scale_x_discrete(expand = c(0,0), labels=c("DI","CJ","CA","TI","NB"))+
        # scale_y_continuous(expand = c(0,0)) +
        facet_wrap(facets = 'site', ncol=2) +
        theme(legend.title = element_blank(),
              legend.key.size = unit(0.3, "cm"),
              legend.text = element_text(size=8 ),
              axis.text.x = element_text(size=8, angle=90, vjust=0.4), 
              strip.text.x = element_text(size = 8),
              legend.position = 'inside',
              legend.position.inside = c(0.7,0.1))

subs.plot

```

```{r table-subs-site}

df_table = cover_year_site[, c('CLASSCODE', 'year','site','percent')]
df_table = df_table %>% pivot_wider(names_from = year, values_from = percent, values_fill = 0)
df_table = df_table[ order(df_table$CLASSCODE), ]

flextable(df_table) %>% autofit() %>% 
  fontsize( size = 8, part='all') %>%
  colformat_double( digits = 1) %>%
  set_table_properties(layout = "autofit")


```

```{r}

df_table2 = cover_year_site[, c('CLASSCODE', 'year','site','percent')]
df_table2 = df_table2 %>% group_by(CLASSCODE,year) %>% summarise(percent = mean(percent))
# df_table2$year = factor(df_table2$year, levels=2015:2025)

df_table2 = df_table2 %>% pivot_wider(names_from = year, values_from = percent, values_fill = 0)


flextable(df_table2) %>% autofit() %>% 
  fontsize( size = 8, part='all') %>%
  colformat_double( digits = 1) %>%
  set_table_properties(layout = "autofit")

```

```{r}

df_table3 = cover_year_site[, c('CLASSCODE', 'year','site','percent')]
df_table3 = df_table3 %>% group_by(CLASSCODE) %>% summarise(percent = mean(percent))
df_table3 = df_table3[ order(df_table3$percent, decreasing = T),]

flextable(df_table3) %>% autofit() %>% 
  fontsize( size = 8, part='all') %>%
  colformat_double( digits = 1) %>%
  set_table_properties(layout = "autofit")


cats = df_table3$CLASSCODE[1:12]

```

```{r}
cover_short = cover_year_site %>% filter(CLASSCODE %in% cats)
subs_color = RColorBrewer::brewer.pal(12,"Paired")

subs.plot2 <- ggplot(cover_short,aes(x=year)) +
        geom_bar(aes(y=percent, fill= CLASSCODE), 
                 position="fill", stat="identity",width = 0.75, colour="black")+
        scale_fill_manual(values = subs_color) +  
        theme(legend.position = "left", aspect.ratio = 3/1)  +
        theme_bw()+
        ylab("Proportion") +
        xlab("") +
        # scale_x_discrete(expand = c(0,0), labels=c("DI","CJ","CA","TI","NB"))+
        # scale_y_continuous(expand = c(0,0)) +
        facet_wrap(facets = 'site', ncol=2) +
        theme(legend.title = element_blank(),
              legend.key.size = unit(0.3, "cm"),
              legend.text = element_text(size=8 ),
              axis.text.x = element_text(size=8, angle=90, vjust=0.4), 
              strip.text.x = element_text(size = 8),
              legend.position = 'inside',
              legend.position.inside = c(0.7,0.1))

subs.plot2

```

```{r nmds-upc}
library(vegan)
df_cover = cover_short[,c('year','site','CLASSCODE','percent')]
df_cover = df_cover %>% pivot_wider(names_from = CLASSCODE, values_from = percent, values_fill = 0)

df_mds = df_cover %>% dplyr::select(-c(year,site))

nmds1 <- metaMDS(df_mds, distance = "bray", k = 3, trymax = 100, trace = FALSE)
nmds1

# plot(nmds1, type = "t", main = paste("NMDS Stress:", round(nmds1$stress, 2)))
# ordiplot(nmds_mod, type = "none", main = "NMDS Colored by Management Type")

site_scores <- as.data.frame(scores(nmds1, display = "sites"))

# Combine the coordinates with your environmental metadata
site_scores$site <- df_cover$site

# Build the ggplot
ggplot(site_scores, aes(x = NMDS1, y = NMDS2, color = site)) +
  geom_point(size = 3) +
  theme_minimal() +
  labs(title = "NMDS via ggplot2",
       subtitle = paste("Stress:", round(nmds1$stress, 2)))
```




