---
title: "Percent Cover"
output:
  html_document: default
  pdf_document: default
---
check on segments that arent done?? 
```{r setup, include=FALSE, message=FALSE, warning=FALSE}
#to load data make sure directory is set to knit from project directory
knitr::opts_chunk$set(echo = FALSE,message=FALSE, warning=FALSE)
 
library(here)
library(tidyverse)
library(knitr)
 
substrate_codes <- read_csv(here("Data","CSV_2015_on","substrate_codes.csv"))

#load 2015 data 
dat.2015 <- read_csv(here("Data", "csv files", "2015_OCNMSDataComplete_standardized_122116.csv")) %>%
  filter(`PISCO datatype` == "UPC") %>%
  separate(Date, into = c("MONTH","DAY","YEAR")) %>%
  rename_all(toupper) %>%
  rename(CLASSCODE= "PISCO CLASSCODE") %>%
  mutate(BUDDY = NA, SEGMENT = NA,SIDE = NA, ZONE = NA, TRANSECT = NA) %>%
  select(SITE, MONTH, DAY, YEAR, OBSERVER, TRANSECT ,QUADRAT, CLASSCODE, PERCENT.COVER,COUNT,DEPTH.FT,SIDE,ZONE,TRANSECT,BUDDY,SEGMENT)
 
#2016 --> 2019
dat.2016 <- read_csv(here("Data","CSV_2015_on","NWFSC_UPC_ALLYEARS_data_2019.csv")) %>% 
              filter(CATEGORY == "COVER") %>%
              select(1:20) %>%
              rename(DEPTH.FT= "DEPTH (FT)")  %>%
              mutate(QUADRAT = NA, PERCENT.COVER = NA) %>% #will circle back tothis and get % cover for 2016 to 2019 data 
              select(SITE, MONTH, DAY, YEAR, OBSERVER, TRANSECT ,QUADRAT, CLASSCODE, PERCENT.COVER,COUNT,DEPTH.FT,SIDE,ZONE,TRANSECT,BUDDY,SEGMENT)

dat.upc <- rbind(dat.2015, dat.2016) %>%
 mutate(COUNT = replace_na(COUNT, 0)) %>%
  left_join(substrate_codes) %>% #rename two that arent in substrate key
  mutate(NAME = case_when(CLASSCODE == "ptero" | NAME == "Pterogophora" ~ "Pterygophora",
                          CLASSCODE == "shell" ~ "various bivalves",
                          TRUE ~ NAME))
 
```


```{r }
#plot species occurence to figure out what should be lumped
dat.upc %>%
  group_by(NAME) %>%
  summarise(species_occurence = sum(COUNT)) %>%
  ggplot() +
  geom_bar(aes(x=reorder(NAME, -species_occurence), y = species_occurence), stat = "identity")+ 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  xlab("Original Species Groups") +
  ylab("Species Count")
 
```


```{r pressure, eval=FALSE}
summary_table<- dat.upc %>%
  group_by(CLASSCODE) %>%
  summarise(species_occurence = sum(COUNT))  %>%
  arrange(desc(species_occurence))
 
print(summary_table)

unique(dat.upc$NAME)
```

## Proposed Lumping 
- Initial thought to do this based on general functional groups 
```{r}
dat.upc.summary <- dat.upc %>%
  group_by(NAME) %>%
  summarise(species_occurence = sum(COUNT)) %>%
  mutate(proposed_new_group = case_when(NAME %in% c("Red algae (branching flat blade)", "Red algae (cylindrical branches", "Red algae (lacy branching)") ~ "Red Algae Branching",
                                    NAME %in% c("Pterygophora", "Brown algae understory prone") ~ "Brown Algae (Understory)",
                                    NAME %in% c("various bivalves", "Scallop") ~ "Bivalve",
                                    NAME %in% c("Anemone", "Cup Coral") ~ "Anthozoa",
                                    NAME %in% c("Red algae -Encrusting", "Coralline algae -Crustose") ~ "Red Corralline Crust",
                                    TRUE ~ NAME)) %>%
  select(proposed_new_group, NAME, species_occurence)
  
  kable(dat.upc.summary)
  
```
 
 
```{r}

ggplot(dat.upc.summary) +
  geom_bar(aes(x=reorder(proposed_new_group, -species_occurence), y = species_occurence), stat = "identity")+ 
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  xlab("New Species Groups") +
  ylab("Species Count")

```
 
 
 